"""wb orchestrator state

Revision ID: 6aec37706b6b
Revises: 3c4d5e6f7a8b
Create Date: 2026-04-26 10:50:34.131277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6aec37706b6b'
down_revision: Union[str, None] = '3c4d5e6f7a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_orchestrator_state',
    sa.Column('user_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(), server_default='idle', nullable=False),
    sa.Column('cooldown_until', sa.String(), nullable=True),
    sa.Column('last_step', sa.String(), nullable=True),
    sa.Column('intents', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_orchestrator_state')
    # ### end Alembic commands ###
