"""operational expenses and pnl operation_expenses

Revision ID: 9625e2645820
Revises: 002
Create Date: 2026-03-23 16:51:50.219197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9625e2645820'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_expenses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_expenses_date'), 'operational_expenses', ['date'], unique=False)
    op.create_index(op.f('ix_operational_expenses_user_id'), 'operational_expenses', ['user_id'], unique=False)
    op.add_column('pnl_daily', sa.Column('operation_expenses', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pnl_daily', 'operation_expenses')
    op.drop_index(op.f('ix_operational_expenses_user_id'), table_name='operational_expenses')
    op.drop_index(op.f('ix_operational_expenses_date'), table_name='operational_expenses')
    op.drop_table('operational_expenses')
    # ### end Alembic commands ###
