"""offer ai chat memory and admin flag

Revision ID: bae96ffe0cd1
Revises: 6aec37706b6b
Create Date: 2026-05-04 18:02:49.439136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bae96ffe0cd1'
down_revision: Union[str, None] = '6aec37706b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_ai_chats',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('offer_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_ai_chats_offer_version'), 'offer_ai_chats', ['offer_version'], unique=False)
    op.create_index(op.f('ix_offer_ai_chats_user_id'), 'offer_ai_chats', ['user_id'], unique=False)
    op.create_table('offer_ai_messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('chat_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('retrieved_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('standalone_question', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('user', 'assistant')", name='ck_offer_ai_message_role'),
    sa.ForeignKeyConstraint(['chat_id'], ['offer_ai_chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_ai_messages_chat_id'), 'offer_ai_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_offer_ai_messages_created_at'), 'offer_ai_messages', ['created_at'], unique=False)
    op.add_column(
        "users",
        sa.Column("is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.alter_column("users", "is_admin", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_offer_ai_messages_created_at'), table_name='offer_ai_messages')
    op.drop_index(op.f('ix_offer_ai_messages_chat_id'), table_name='offer_ai_messages')
    op.drop_table('offer_ai_messages')
    op.drop_index(op.f('ix_offer_ai_chats_user_id'), table_name='offer_ai_chats')
    op.drop_index(op.f('ix_offer_ai_chats_offer_version'), table_name='offer_ai_chats')
    op.drop_table('offer_ai_chats')
    # ### end Alembic commands ###
