"""billing webhook events dedupe

Revision ID: ca01bc007d73
Revises: f5005a06ca10
Create Date: 2026-03-26 19:03:52.531291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca01bc007d73'
down_revision: Union[str, None] = 'f5005a06ca10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('event_key', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_index(op.f('ix_webhook_events_provider'), 'webhook_events', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_provider'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
